# Generated by Django 2.1 on 2018-08-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0002_auto_20180823_2015'),
        ('sub', '0002_auto_20180823_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('banned_list', models.ManyToManyField(blank=True, default=None, related_name='all_bannedlist', to='userlist.Vser')),
                ('moderators', models.ManyToManyField(blank=True, related_name='all_modlist', to='userlist.Vser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_owner', to='userlist.Vser')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='all_subslist', to='userlist.Vser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='class',
            name='banned_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='class_bannedlist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='class',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='class_modlist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='class_subslist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='banned_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='clubs_bannedlist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='clubs_modlist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='clubs_subslist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='news',
            name='banned_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='news_bannedlist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='news',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='news_modlist', to='userlist.Vser'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='news_subslist', to='userlist.Vser'),
        ),
    ]
