# Generated by Django 2.1 on 2018-08-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_auto_20180823_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
    ]
