# Generated by Django 2.1 on 2018-08-23 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailid', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('karma', models.IntegerField(default=0)),
                ('flair', models.CharField(blank=True, max_length=30, null=True)),
                ('banned', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('cakeday', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moderator',
            name='mod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userlist.Vser'),
        ),
    ]
