# Generated by Django 2.1 on 2018-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vser',
            name='cakeday',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
